# Generated by Django 5.2.8 on 2025-11-30 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthprofile',
            options={'verbose_name': 'Health Profile', 'verbose_name_plural': 'Health Profiles'},
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='alcohol_consumption',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('occasional', 'Occasional'), ('regular', 'Regular')], max_length=50),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='exercise_frequency',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('light', '1-2 times per week'), ('moderate', '3-4 times per week'), ('active', '5+ times per week')], max_length=50),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='family_history',
            field=models.TextField(blank=True, help_text='Family medical history'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='insurance_group',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='insurance_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='primary_doctor_clinic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='primary_doctor_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='primary_doctor_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='smoking_status',
            field=models.CharField(blank=True, choices=[('never', 'Never smoked'), ('former', 'Former smoker'), ('current', 'Current smoker')], max_length=50),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='surgical_history',
            field=models.TextField(blank=True, help_text='Previous surgeries with dates'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text='List all allergies separated by commas'),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Unknown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='current_medications',
            field=models.TextField(blank=True, help_text='List current medications with dosage'),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='Chronic conditions or diagnoses'),
        ),
    ]
